version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.0-stretch
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test:
    docker:
      - image: circleci/node:12.9.0-stretch
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: Build JS
          command: yarn build
       - run:
         name: Lint
         command: yarn lint
      - run:
          name: Test
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
